### ISSUE TITLE
Error: buffer is too small for requested array when try to convert weights for yolov4 tiny

### ISSUE THREAD

**Issue by waheed0332** [MPieter/YOLOv4-CoreML-Converter#2]
Concatenating route layers: [<tf.Tensor 'up_sampling2d/Identity:0' shape=(None, 26, 26, 128) dtype=float32>, <tf.Tensor 'leaky_re_lu_13/Identity:0' shape=(None, 26, 26, 256) dtype=float32>]
Parsing section convolutional_19
conv2d bn leaky (3, 3, 384, 256)
Traceback (most recent call last):
  File "convert.py", line 305, in <module>
    _main(parser.parse_args())
  File "convert.py", line 181, in _main
    buffer=weights_file.read(weights_size * 4))
TypeError: buffer is too small for requested array

**Comment by MPieter** [comment]
This typically occurs when your config and weight file don't match.

**Comment by waheed0332** [comment]
Ok, but I'm using weights and cfgs from the official repo. Can you share test weights and cfg links?

**Comment by waheed0332** [comment]
@MPieter I tried this using weights and cfg from the official repo but still getting the same error. Can you look through that?

**Comment by MPieter** [comment]
I use the config and model files from following website:
https://github.com/AlexeyAB/darknet/wiki/YOLOv4-model-zoo


The script was using a fixed 416x416 input resolution but I changed this to using a parameter.

**Comment by waheed0332** [comment]
This doesn't have a tiny model in the zoo so grab weights and cfg from the main page.
Cfg: https://raw.githubusercontent.com/AlexeyAB/darknet/master/cfg/yolov4-tiny.cfg
Weights: https://github.com/AlexeyAB/darknet/releases/download/darknet_yolo_v4_pre/yolov4-tiny.weights

**Comment by ClementLeBihan** [comment]
Hi,
I've got the same problem. Any solution ?
